title: Gerby's Doc Starter Site
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://gerbyjj.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

kramdown:
  toc_levels: 2..3

plugins:
  - jekyll-multiple-languages-plugin
  
languages: ["en", "client1", "client2"]
default_locale_in_subfolder: false

exclude_from_localizations: ["javascript", "images", "css"]
